---
# tasks file for users

- name: Create New User
  ansible.builtin.user:
    name: "{{ username }}"
    groups: "{{ usergroup }}"
    password: "{{ default_user_password | password_hash('sha512') }}"
    update_password: on_create
    state: present

- name: Deploy SSH Public Key
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ ssh_public_key }}"
